# Setup


In [1]:
# Import packages
import cv2
import matplotlib.pyplot as plt
import numpy as np

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.


In [2]:
# Read images
image1 = cv2.imread('Images/Image6.jpg') # Russian Taxi at Angle and Some Distance
image2 = cv2.imread('Images/Image7.jpg') # Two Russian Plates with Telephoto Lens
image3 = cv2.imread('Images/Image4.jpg') # Ontario Plate
source = list([image1, image2, image3])
# https://www.geeksforgeeks.org/how-to-fix-valueerror-setting-an-array-element-with-a-sequence/
source = np.array(source, dtype = list)

# Define placeholders
gray = np.array([0, 1, 2], dtype = list)
plates = np.array(list(range(3)), dtype = list)
plateszoom = np.array(list(range(3)), dtype = list)

# Convert to Grayscale
for i in range(len(source)):
    gray[i] = cv2.cvtColor(source[i], cv2.COLOR_BGR2GRAY)

# # Load Classifier
rusPlateReader = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_license_plate_rus_16stages.xml')
rusPlateFinder = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_russian_plate_number.xml')

# Detect Plates

In [4]:
# Detect Plates
# https://github.com/kennethleungty/Car-Plate-Detection-OpenCV-TesseractOCR/blob/main/Car%20Plate%20Detection%20with%20OpenCV%20and%20TesseractOCR.ipynb
def CarplateDetect(image):
    # Color rectangle overlay on grayscale image plate detection area
    carplate_overlay = cv2.cvtColor(image.copy(), cv2.COLOR_GRAY2BGR)
    carplate_rects = rusPlateFinder.detectMultiScale(carplate_overlay,
                                                     scaleFactor = 1.1,
                                                     minNeighbors = 5) 
    # carplate_img = 0

    for x, y, w, h in carplate_rects:
        cv2.rectangle(carplate_overlay,
                      (x, y),
                      (x + w, y + h),
                      (255, 0, 0),
                      25) 
        
    # for x, y, w, h in carplate_rects:
    #     carplate_img = carplate_overlay[y + 15: y + h - 10,
    #                          x + 15: x + w - 20] 


    return carplate_overlay

In [26]:
carplate_overlay = image2.copy()
carplate_rects = rusPlateFinder.detectMultiScale(carplate_overlay,
                                                    scaleFactor = 1.1,
                                                    minNeighbors = 5) 

for x, y, w, h in carplate_rects:
    cv2.rectangle(carplate_overlay,
                    (x, y),
                    (x + w, y + h),
                    (255, 0, 0),
                    25)

# Zoom on Plates

## Works

In [9]:
def PlateZoom(image):
    carplate_overlay = cv2.cvtColor(image.copy(), cv2.COLOR_GRAY2BGR)
    carplate_rects = rusPlateFinder.detectMultiScale(carplate_overlay,
                                                     scaleFactor = 1.1,
                                                     minNeighbors = 5)
    for x, y, w, h in carplate_rects:
        carplate_img = carplate_overlay[y + 15: y + h - 10,
                             x + 15: x + w - 20]
    return carplate_img

In [6]:
def carplate_extract(image):
    
    carplate_rects = rusPlateFinder.detectMultiScale(image,scaleFactor=1.1, minNeighbors=5) 

    plates_x = min(carplate_rects[:, 0])
    plates_y = min(carplate_rects[:, 1])
    plates_h = max(carplate_rects[:, 3])
    plates_w = max(carplate_rects[:, 2])
    carplate_img = image[plates_y : plates_y + plates_h, plates_x : plates_x + plates_w]

    return carplate_img

## Experimenting

In [95]:
carplate_rects = rusPlateFinder.detectMultiScale(gray[1],
                                                     scaleFactor = 1.1,
                                                     minNeighbors = 5)

In [96]:
carplate_rects

array([[218, 531, 190,  63],
       [881, 577, 265,  89]], dtype=int32)

In [97]:
carplate_rects_0 = carplate_rects[0]
carplate_rects_1 = carplate_rects[1]

In [100]:
def SemiZoom(image, overlay):
    image = overlay[image[1]:image[1]+image[3],
                    image[0]:image[0]+image[2]]
    return image

In [98]:
carplate_overlay = cv2.cvtColor(gray[1].copy(), cv2.COLOR_GRAY2BGR)

In [109]:
# carplate_rects = rusPlateFinder.detectMultiScale(gray[1],
#                                                      scaleFactor = 1.1,
#                                                      minNeighbors = 5)
# carplate_overlay = cv2.cvtColor(gray[1].copy(), cv2.COLOR_GRAY2BGR)
# carplate_rects_0 = carplate_rects[0]
# carplate_rects_1 = carplate_rects[1]
# plates[1] = CarplateDetect(gray[1])
plateszoom_1 = SemiZoom(carplate_rects_0, carplate_overlay)
plateszoom_2 = SemiZoom(carplate_rects_1, carplate_overlay)

In [107]:
plateszoom_1

array([[[26, 26, 26],
        [23, 23, 23],
        [27, 27, 27],
        ...,
        [82, 82, 82],
        [83, 83, 83],
        [88, 88, 88]],

       [[39, 39, 39],
        [44, 44, 44],
        [43, 43, 43],
        ...,
        [82, 82, 82],
        [81, 81, 81],
        [85, 85, 85]],

       [[44, 44, 44],
        [51, 51, 51],
        [47, 47, 47],
        ...,
        [87, 87, 87],
        [85, 85, 85],
        [88, 88, 88]],

       ...,

       [[16, 16, 16],
        [17, 17, 17],
        [18, 18, 18],
        ...,
        [13, 13, 13],
        [13, 13, 13],
        [13, 13, 13]],

       [[16, 16, 16],
        [17, 17, 17],
        [16, 16, 16],
        ...,
        [12, 12, 12],
        [12, 12, 12],
        [13, 13, 13]],

       [[14, 14, 14],
        [15, 15, 15],
        [14, 14, 14],
        ...,
        [11, 11, 11],
        [11, 11, 11],
        [12, 12, 12]]], dtype=uint8)

In [104]:
plateszoom

array([[[ 58,  58,  58],
        [ 55,  55,  55],
        [ 52,  52,  52],
        ...,
        [ 12,  12,  12],
        [ 14,  14,  14],
        [ 20,  20,  20]],

       [[ 60,  60,  60],
        [ 57,  57,  57],
        [ 53,  53,  53],
        ...,
        [ 12,  12,  12],
        [ 20,  20,  20],
        [ 19,  19,  19]],

       [[ 66,  66,  66],
        [ 63,  63,  63],
        [ 60,  60,  60],
        ...,
        [ 13,  13,  13],
        [ 24,  24,  24],
        [ 19,  19,  19]],

       ...,

       [[171, 171, 171],
        [171, 171, 171],
        [171, 171, 171],
        ...,
        [  7,   7,   7],
        [  9,   9,   9],
        [ 14,  14,  14]],

       [[171, 171, 171],
        [171, 171, 171],
        [171, 171, 171],
        ...,
        [  8,   8,   8],
        [ 10,  10,  10],
        [ 14,  14,  14]],

       [[171, 171, 171],
        [171, 171, 171],
        [171, 171, 171],
        ...,
        [ 11,  11,  11],
        [ 12,  12,  12],
        [ 14,  14,  14]]

In [88]:
plateszoom = SemiZoom(carplate_rects_0, carplate_overlay)

In [82]:
def PlateZoom(image):
    carplate_overlay = cv2.cvtColor(image.copy(), cv2.COLOR_GRAY2BGR)
    carplate_rects = rusPlateFinder.detectMultiScale(carplate_overlay,
                                                     scaleFactor = 1.1,
                                                     minNeighbors = 5)
    if len(carplate_rects) < 2:
        for x, y, w, h in carplate_rects:
            carplate_img = carplate_overlay[y + 15: y + h - 10,
                                x + 15: x + w - 20]
    else:
        for i in range(0, len(carplate_rects)):
            carplate_rects_stage = carplate_rects[i]
            SemiZoom(carplate_rects_stage, carplate_overlay)
        exit
    return carplate_img

In [91]:
plateszoom = PlateZoom(gray[0])

In [83]:
plateszoom = PlateZoom(gray[1])

UnboundLocalError: cannot access local variable 'carplate_img' where it is not associated with a value

In [32]:
carplate_rects

array([[881, 577, 265,  89],
       [218, 531, 190,  63]], dtype=int32)

In [112]:
cv2.imshow("test", plateszoom_1)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Plot Results

In [7]:
plates = CarplateDetect(gray[0])
plateszoom = carplate_extract(gray[0])

In [25]:
carplate_rects = rusPlateFinder.detectMultiScale(gray[1],scaleFactor=1.1, minNeighbors=5) 

In [13]:
# cv2.imshow("test", plates)
cv2.imshow("test", plateszoom)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [58]:
for i in range(len(source)):
    plates[i] = CarplateDetect(gray[i])
    plateszoom[i] = carplate_extract(gray[i])

TypeError: tuple indices must be integers or slices, not tuple

In [5]:
for i in range(len(source)):
    plates[i] = CarplateDetect(gray[i])
    # plateszoom[i] = carplate_extract(gray[i])

images = [plates[0], plates[1], plates[2],
          plateszoom[0], plateszoom[1], plateszoom[2]]

In [ ]:
for i in range(3):
    plt.subplot(3, 2, i + 1), plt.imshow(plates[i], 'gray')
    plt.xticks([]), plt.yticks([])
    # plt.title(titles[i])
    plt.tight_layout()
# plt.suptitle('Edge Detection Results', fontsize = 25).set_color('#171819')
plt.tight_layout()
plt.show()