In [68]:
# Inspiration from https://github.com/simpleai-team/simpleai/blob/master/samples/search/eight_puzzle.py

from simpleai.search import astar, SearchProblem
from simpleai.search.viewers import WebViewer
import numpy as np
import math

# Intial and Goal states

initial_state = [['7', '6', '5'],
                 ['4', '3', '2'],
                 ['1', '8', 'empty']]

goal_state = [['1', '2', '3'],
              ['4', '5', '6'],
              ['7', '8', 'empty']]

initial_state_np = np.array([[7, 6, 5],
                             [4, 3, 2],
                             [1, 8, 0]])
goal_state_np = np.array([[1, 2, 3],
                          [4, 5, 6],
                          [7, 8, 0]])

In [66]:
# Functions
'''
Using this source to find pieces around the empty space that could move.
https://www.geeksforgeeks.org/find-all-adjacent-elements-of-given-element-in-a-2d-array-or-matrix/
'''
def isValidPos(i, j, row, column):
    if (i < 0 or j < 0 or i > row - 1 or j > column - 1):
        return 0
    return 1
 
 
# Find all adjacent elements, including diagonal matches
def getAdjacent(array, i, j):
    row, column = len(array), len(array[0])
    adjacentvalues = []

    if (isValidPos(i - 1, j - 1, row, column)):
        adjacentvalues.append(array[i - 1][j - 1])
    if (isValidPos(i - 1, j, row, column)):
        adjacentvalues.append(array[i - 1][j])
    if (isValidPos(i - 1, j + 1, row, column)):
        adjacentvalues.append(array[i - 1][j + 1])
    if (isValidPos(i, j - 1, row, column)):
        adjacentvalues.append(array[i][j - 1])
    if (isValidPos(i, j + 1, row, column)):
        adjacentvalues.append(array[i][j + 1])
    if (isValidPos(i + 1, j - 1, row, column)):
        adjacentvalues.append(array[i + 1][j - 1])
    if (isValidPos(i + 1, j, row, column)):
        adjacentvalues.append(array[i + 1][j])
    if (isValidPos(i + 1, j + 1, row, column)):
        adjacentvalues.append(array[i + 1][j + 1])
 
    return adjacentvalues


'''
Source: https://www.geeksforgeeks.org/how-to-find-the-index-of-value-in-numpy-array/
numpy.where() kept giving invalid entries, and this is one of the shortest methods of getting something usable
'''
def ind(array, item):
    for index, value in np.ndenumerate(array):
        if value == item:
            return index


# https://www.geeksforgeeks.org/calculate-the-manhattan-distance-between-two-cells-of-given-2d-array/
def manhattanDistance(firstvector, secondvector):
    dist = math.fabs(secondvector[0] - firstvector[0]) + math.fabs(secondvector[1] - firstvector[1])
    return (int)(dist)


def manhattanAStar(initial, goal):
    counter = 0
    # Start state is Goal State
    if np.sum(np.square(np.subtract(initial, (goal)))) == 0:
        print('\nInitial state is goal state. No moves required.\n')
    else:
        # Perform this function until array reaches the goal state
        print(f'\nInitial state is:\n{initial}')
        # return initial
        while np.sum(np.square(np.subtract(initial, (goal)))) != 0:
            # Find movable pieces. Assume diagonal movement allowed.
            adjacents = getAdjacent(initial, ind(initial, 0)[0], ind(initial, 0)[1])
            # Initialize array
            difference_matrix = np.empty(len(adjacents))
            # Find minimum movement distance
            for i in range(len(adjacents)):
                difference_matrix[i] = manhattanDistance(list(ind(initial, adjacents[i])),
                                                            list(ind(goal, adjacents[i])))
            # Swap best piece with empty space, record new array
            print(f'\nMove piece {adjacents[ind(difference_matrix, np.amin(difference_matrix))[0] != 0]}')
            emptyspace = initial[ind(initial, 0)]
            swappiece = initial[ind(initial, adjacents[ind(difference_matrix, np.amin(difference_matrix))[0] != 0])]
            initial[ind(initial, 0)], initial[ind(initial, swappiece)] = swappiece, 0
            print(initial)
            # Swap syntax breaks at this point, but concept should reach solution once the error is fixed
            if counter > 3:
                break
            else:
                counter += 1
        print(f'Solution took {counter} moves to reach goal.\n{goal}')

In [69]:
manhattanAStar(initial_state_np, goal_state_np)


Initial state is:
[[7 6 5]
 [4 3 2]
 [1 8 0]]

Move piece 2
[[7 6 5]
 [4 3 0]
 [1 8 2]]

Move piece 5
[[7 6 0]
 [4 3 5]
 [1 8 2]]

Move piece 3
[[7 6 0]
 [4 3 5]
 [1 8 2]]

Move piece 3
[[7 6 0]
 [4 3 5]
 [1 8 2]]

Move piece 3
[[7 6 0]
 [4 3 5]
 [1 8 2]]
Solution took 4 moves to reach goal.
[[1 2 3]
 [4 5 6]
 [7 8 0]]
